trigger:
- main

pool:
  name: 'Default'
  demands:
    - agent.name -equals LOKMANE

variables:
  azureSubscription: 'Azureserviceconnection'  # Your Azure service connection name
  frontendImageName: 'azurecontainerregistryconnection.azurecr.io/frontend'
  backendImageName: 'azurecontainerregistryconnection.azurecr.io/backend'
  frontendAppName: 'frontend-app-service'  # Your Azure App Service name for frontend
  backendAppName: 'backend-app-service'  # Your Azure App Service name for backend

steps:
# Step 1: Checkout the code from the new repository
- checkout: self
  persistCredentials: true

# Step 2: Log in to Azure Container Registry (ACR) using service connection
- task: Docker@2
  displayName: Login to Azure Container Registry
  inputs:
    command: login
    containerRegistry: 'AzureDockerConnection'  # The name of your docker registry service connection

# Step 3: Build and push the frontend Docker image
- task: Docker@2
  displayName: Build and Push Frontend Image
  inputs:
    command: buildAndPush
    repository: $(frontendImageName)
    dockerfile: ./frontend/Dockerfile
    containerRegistry: 'AzureDockerConnection'
    tags: |
      latest
      $(Build.BuildId)

# Step 4: Build and push the backend Docker image
- task: Docker@2
  displayName: Build and Push Backend Image
  inputs:
    command: buildAndPush
    repository: $(backendImageName)
    dockerfile: ./backend/Dockerfile
    containerRegistry: 'AzureDockerConnection'
    tags: |
      latest
      $(Build.BuildId)

# Step 5: Deploy the frontend service to Azure App Service
- task: AzureWebAppContainer@1
  displayName: Deploy Frontend to Azure App Service
  inputs:
    azureSubscription: $(azureSubscription)
    appName: $(frontendAppName)
    imageName: $(frontendImageName)
    slot: 'fhckdydvg8efgvdu'  # Ensure this matches the slot name

# Step 6: Deploy the backend service to Azure App Service
- task: AzureWebAppContainer@1
  displayName: Deploy Backend to Azure App Service
  inputs:
    azureSubscription: $(azureSubscription)
    appName: $(backendAppName)
    imageName: $(backendImageName)
    slot: 'fhckdydvg8efgvdu'  # Ensure this matches the slot name
